/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Calendar: typeof import('./src/components/calendar/Calendar.vue')['default']
    CalendarDay: typeof import('./src/components/calendar/CalendarDay.vue')['default']
    CalendarEvent: typeof import('./src/components/calendar/CalendarEvent.vue')['default']
    CalendarGrid: typeof import('./src/components/calendar/CalendarGrid.vue')['default']
    CalendarHeader: typeof import('./src/components/calendar/CalendarHeader.vue')['default']
    CalendarWeekdays: typeof import('./src/components/calendar/CalendarWeekdays.vue')['default']
    Check1: typeof import('./src/components/check1.vue')['default']
    Check2: typeof import('./src/components/calendar/check2.vue')['default']
    Check3: typeof import('./src/components/check3.vue')['default']
    Check4: typeof import('./src/components/check4.vue')['default']
    H1: typeof import('./src/components/H1.vue')['default']
    H2: typeof import('./src/components/H2.vue')['default']
    H3: typeof import('./src/components/H3.vue')['default']
    H4: typeof import('./src/components/H4.vue')['default']
    H5: typeof import('./src/components/H5.vue')['default']
    H6: typeof import('./src/components/H6.vue')['default']
    H7: typeof import('./src/components/H7.vue')['default']
    H8: typeof import('./src/components/H8.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
