/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    CalendarDay: typeof import('./src/components/CalendarDay.vue')['default']
    CalendarEvent: typeof import('./src/components/CalendarEvent.vue')['default']
    CalendarEventItem: typeof import('./src/components/CalendarEventItem.vue')['default']
    CalendarGrid: typeof import('./src/components/CalendarGrid.vue')['default']
    CalendarHeader: typeof import('./src/components/CalendarHeader.vue')['default']
    CalendarWeekdays: typeof import('./src/components/CalendarWeekdays.vue')['default']
    H1: typeof import('./src/components/H1.vue')['default']
    H2: typeof import('./src/components/H2.vue')['default']
    H3: typeof import('./src/components/H3.vue')['default']
    H4: typeof import('./src/components/H4.vue')['default']
    H5: typeof import('./src/components/H5.vue')['default']
    H6: typeof import('./src/components/H6.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ParkingDateSelector: typeof import('./src/components/ParkingDateSelector.vue')['default']
    ParkingHeader: typeof import('./src/components/ParkingHeader.vue')['default']
    ParkingTimeInfo: typeof import('./src/components/ParkingTimeInfo.vue')['default']
    ParkingTimeSelector: typeof import('./src/components/ParkingTimeSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeSlot: typeof import('./src/components/TimeSlot.vue')['default']
  }
}
